"""Write the paper's foreground_svd.npz from position_sims.npz's nominal row.

Until 2026-09-11 this file had no generator anywhere: every notebook read it,
nothing wrote it, and `horizon_shift.ipynb` asserts byte-equality of its t_sys
against `position_sims.npz` row 0 -- so any change to the terrain model broke
the pipeline with no committed way to rebuild the deposit. This closes that.

It carries no independent information. `t_sys`/`fgnd` are row 0 of
position_sims verbatim; `time_hr` is derived from its `times_jd`; everything
else is metadata. Run it after `run_sims.py`, before the notebooks:

    uv run python horizon_position/make_foreground_svd.py

Output: the paper repo's foreground_svd.npz (see paper.PAPER, overridable with
EIGSEP_PAPER_NOTEBOOKS). Pass --check to verify the existing file matches
without writing.

A plain run REFUSES to overwrite a deposit whose arrays differ from what it
would write, so a stray run cannot silently move the published figures;
`--force` overrides when the figures are being regenerated deliberately. The
round-2 deposit is archived under output/rasti_round2_deposit/.
"""

import argparse
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import paper  # noqa: E402

FG_NPZ = paper.PAPER / "foreground_svd.npz"

# The beam is not recorded in position_sims.npz; it is fixed by the eigsim
# config run_sims.py uses and is restated here so the deposit is self-describing.
BEAM = "eigsep_bowtie_v000_mwss"

DESCRIPTION = """\
EIGSEP baseline zenith waterfall for the foreground-SVD figure. Bowtie beam, \
GSM16 sky, T_ground=300 K, T_receiver=50 K, realistic horizon, fixed zenith \
pointing, one sidereal day. 't_sys' is the system temperature (n_time, n_freq) \
[K]. Ground-loss correct with t_sky = (t_sys - t_receiver - fgnd*t_ground)/\
(1 - fgnd) to recover the beam-weighted sky temperature, then SVD the \
uncentered time-frequency waterfall. Generated by \
mock_analysis/horizon_position/make_foreground_svd.py from position_sims.npz \
(nominal row).

LOAD-BEARING: this file's t_sys is byte-identical (np.array_equal) to \
position_sims.npz row 0 ('nominal'), and it is the SOURCE from which the Vh \
foreground eigenmode basis is derived in-notebook (svd(t_sys - t_receiver), \
uncentered) for both horizon_shift.pdf and beam_comparison.pdf -- see \
horizon_shift.npz's params and test_vh_derives_from_foreground_svd_to_curve_\
precision. It was nearly deleted as an orphan during the figure-workflow NPZ \
audit before this dependency was traced; it must not be removed. Since \
2026-09-11 position_sims.npz is itself deposited, so this file is the small \
single-position slice a reader needs for the figures, with the full 19-position \
run behind it for anyone checking the analysis.

It is NOT superseded by beam_comparison.npz's bowtie row (beam_sims.npz in \
mock_analysis): that is a SEPARATE eigsim run (same beam, sky, horizon, and \
nominal position) whose t_sys differs from this file's at the 1e-7 relative \
level (np.array_equal is False, i.e. NOT byte-identical). \
test_beam_comparison_beams_are_in_the_figure_order already checks that this \
difference stays under 1e-5; do not treat the two arrays as interchangeable or \
assume either can replace the other."""


def build():
    """Return the npz payload, read straight out of position_sims.npz."""
    s = np.load(paper.SIMS_NPZ, allow_pickle=True)
    names = [str(n) for n in s["names"]]
    i = names.index("nominal")
    tj = s["times_jd"]
    enu = np.asarray(s["enu"])[i]

    params = (
        f"beam={BEAM!r} (beam_lmax={int(s['beam_lmax'])}); "
        f"sky_model={str(s['sky_model'])!r}; t_ground={float(s['t_ground']):g} K; "
        f"t_receiver={float(s['t_receiver']):g} K; site lon={float(s['lon']):g} deg, "
        f"lat={float(s['lat']):g} deg, alt={float(s['alt']):g} m; "
        f"t_start={str(s['t_start'])}; n_times={int(s['n_times'])} "
        f"(one sidereal day); position: nominal ENU = "
        f"[{enu[0]:g}, {enu[1]:g}, {enu[2]:g}] m (position_sims.npz row 0). "
        "Ground-loss correction: t_sky = (t_sys - t_receiver - fgnd*t_ground) / "
        "(1 - fgnd). SVD: np.linalg.svd(t_sys - t_receiver, full_matrices=False), "
        "uncentered."
    )
    provenance = (
        f"Built by mock_analysis/horizon_position/make_foreground_svd.py from "
        f"horizon_position/output/position_sims.npz row 0 (names[0]='nominal'), "
        f"pos_sha {str(s['pos_sha'])}, eigsim_version {str(s['eigsim_version'])}. "
        "pos_sha hashes the antenna POSITIONS only -- it does not change when the "
        "terrain model does, so it is not a staleness guard for the DEM."
    )
    return dict(
        t_sys=s["t_sys"][i],
        fgnd=s["fgnd"][i],
        t_ground=s["t_ground"],
        t_receiver=s["t_receiver"],
        freqs_MHz=s["freqs_mhz"],
        time_hr=(tj - tj[0]) * 24.0,
        sky_model=s["sky_model"],
        beam=np.array(BEAM),
        eigsim_version=s["eigsim_version"],
        description=DESCRIPTION,
        params=params,
        provenance=provenance,
    )


#: Arrays the deposit is judged on: the load-bearing ones, not the metadata.
CHECKED_KEYS = ("t_sys", "fgnd", "freqs_MHz", "time_hr", "t_ground", "t_receiver")


def differing_keys(out):
    """Which of CHECKED_KEYS in the existing deposit differ from ``out``.

    Raises FileNotFoundError if there is no deposit yet.
    """
    have = np.load(FG_NPZ, allow_pickle=True)
    return [
        k
        for k in CHECKED_KEYS
        if not np.array_equal(np.asarray(have[k]), np.asarray(out[k]))
    ]


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--check",
        action="store_true",
        help="compare against the existing file instead of writing",
    )
    p.add_argument(
        "--force",
        action="store_true",
        help="overwrite an existing deposit whose arrays differ (see __doc__)",
    )
    args = p.parse_args()

    out = build()
    if args.check:
        bad = differing_keys(out)
        print(f"{FG_NPZ}: arrays {'MATCH' if not bad else 'DIFFER: ' + ', '.join(bad)}")
        raise SystemExit(1 if bad else 0)

    if not args.force and FG_NPZ.exists():
        # Same comparison --check makes: refuse to replace a deposit that
        # does not already agree with position_sims.npz row 0. A deposit that
        # disagrees is the input to figures that are already committed, so
        # writing without being asked would silently move them.
        bad = differing_keys(out)
        if bad:
            raise SystemExit(
                f"REFUSING to overwrite {FG_NPZ}: it differs from what this run "
                f"would write ({', '.join(bad)}).\n"
                f"Source: {paper.SIMS_NPZ} row 0. The deposit on disk is the "
                "input to the committed figures, so this would replace it "
                "under them.\n"
                "Pass --force only when the paper's figures are being "
                "regenerated deliberately."
            )

    np.savez(FG_NPZ, **out)
    print(f"Saved {FG_NPZ}  t_sys {out['t_sys'].shape}")


if __name__ == "__main__":
    main()
