"""Where the paper's artifacts live, and the constants the two figures share.

Deliberately holds no analysis. `notebooks/horizon_shift.ipynb` and
`notebooks/signal_loss.ipynb` each derive the operating point and the 21 cm
selection from the raw inputs and then assert against the values here, so
these constants are a *contract* between the two figures rather than a
shortcut around either derivation. If a regenerated ensemble moves one of
them, both notebooks fail loudly instead of quietly disagreeing.

`EIGSEP_PAPER_NOTEBOOKS` overrides the output location, so a generator can be
pointed at a worktree instead of writing into the live paper directory.
"""

import os
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

# The paper repo's notebooks/ dir: a committed npz + a standalone notebook
# that regenerates the PDF, with the npz archived to Zenodo separately.
PAPER = Path(
    os.environ.get(
        "EIGSEP_PAPER_NOTEBOOKS",
        "/home/christian/Documents/research/papers/eigsep_instrument/notebooks",
    )
)
FG_NPZ = PAPER / "foreground_svd.npz"
SHIFT_NPZ = PAPER / "horizon_shift.npz"
SIGNAL_LOSS_NPZ = PAPER / "signal_loss.npz"

# Simulation output (gitignored; see README.md for the regeneration commands).
SIMS_NPZ = HERE / "output" / "position_sims.npz"
HORIZONS_NPZ = HERE / "output" / "horizons_position.npz"

# Generated by models_21cm/generate.py from Zeus21 (Munoz 2023a,
# arXiv:2302.08506) with Pop III and Lyman-Werner feedback (Cruz+2024,
# arXiv:2407.18294). The npz carries its own regeneration recipe: read its
# `provenance`, `generator_source` and `env_lock` keys. Spec:
# docs/superpowers/specs/2026-08-19-zeus21-model-ensemble-design.md
MODELS_NPZ = ROOT / "models_21cm" / "output" / "zeus21_models.npz"

# The subspace dimension the figures illustrate at. NOT a filter depth anyone
# proposes to apply to data: signal_loss.pdf needs *a* depth to draw panel (a2)
# and to colour by, and this is it. Derived as the smallest N at which the
# foreground residual falls below the median retained 21 cm signal and *stays*
# below for every larger N -- a legibility criterion, not a policy, because
# that residual is an in-sample optimum (horizon_shift.ipynb, section 6) and so
# not a benchmark real data could be held to.
#
# It happens to land where horizon_shift.ipynb shows the limit changing hands:
# below N ~ 8 the foregrounds are the larger term by 2-6x, from N ~ 9 they are
# comparable to what a 1 m vertical position error leaves, and beyond N ~ 12
# the position error is consistently larger. That is the meaningful landmark,
# it is a result of the horizon analysis rather than of this criterion, and it
# is stated there. Both notebooks re-derive this value and assert it.
N_ANCHOR = 9

# Foreground modes on the residual panels' x-axis, in both figures.
N_SHOW = 18

# Models surviving selection.reionized_across_band out of the 4096 generated.
# Asserted in both notebooks so the two figures cannot cut different ensembles.
N_MODELS = 1769
