"""Where the paper's artifacts live, and the constants the two figures share.

Deliberately holds no analysis. `notebooks/horizon_shift.ipynb` and
`notebooks/signal_loss.ipynb` each derive the operating point and the 21 cm
selection from the raw inputs and then assert against the values here, so
these constants are a *contract* between the two figures rather than a
shortcut around either derivation. If a regenerated ensemble moves one of
them, both notebooks fail loudly instead of quietly disagreeing.

`EIGSEP_PAPER_NOTEBOOKS` overrides the output location, so a generator can be
pointed at a worktree instead of writing into the live paper directory.
"""

import os
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

# The paper repo's notebooks/ dir: a committed npz + a standalone notebook
# that regenerates the PDF, with the npz archived to Zenodo separately.
PAPER = Path(
    os.environ.get(
        "EIGSEP_PAPER_NOTEBOOKS",
        "/home/christian/Documents/research/papers/eigsep_instrument/notebooks",
    )
)
FG_NPZ = PAPER / "foreground_svd.npz"
SHIFT_NPZ = PAPER / "horizon_shift.npz"
SIGNAL_LOSS_NPZ = PAPER / "signal_loss.npz"

# Simulation output (gitignored; see README.md for the regeneration commands).
SIMS_NPZ = HERE / "output" / "position_sims.npz"
HORIZONS_NPZ = HERE / "output" / "horizons_position.npz"

# Generated by models_21cm/generate.py from Zeus21 (Munoz 2023a,
# arXiv:2302.08506) with Pop III and Lyman-Werner feedback (Cruz+2024,
# arXiv:2407.18294). The npz carries its own regeneration recipe: read its
# `provenance`, `generator_source` and `env_lock` keys. Spec:
# docs/superpowers/specs/2026-08-19-zeus21-model-ensemble-design.md
MODELS_NPZ = ROOT / "models_21cm" / "output" / "zeus21_models.npz"

# Modes filtered at the quoted operating point. Set by the foreground residual
# alone -- the smallest N at which it falls below the median retained 21 cm
# signal and *stays* below for every larger N. Both notebooks re-derive this
# and assert it still equals this value.
N_ANCHOR = 9

# Foreground modes on the residual panels' x-axis, in both figures.
N_SHOW = 18

# Models surviving selection.reionized_across_band out of the 4096 generated.
# Asserted in both notebooks so the two figures cannot cut different ensembles.
N_MODELS = 1769
