"""Where the paper's artifacts live, and the constants the two figures share.

Deliberately holds no analysis. `notebooks/horizon_shift.ipynb` and
`notebooks/signal_loss.ipynb` each derive the operating point and the 21 cm
selection from the raw inputs and then assert against the values here, so
these constants are a *contract* between the two figures rather than a
shortcut around either derivation. If a regenerated ensemble moves one of
them, both notebooks fail loudly instead of quietly disagreeing.

`EIGSEP_PAPER_NOTEBOOKS` overrides the output location, so a generator can be
pointed at a worktree instead of writing into the live paper directory.
"""

import os
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

# The paper repo's notebooks/ dir: a committed npz + a standalone notebook
# that regenerates the PDF, with the npz archived to Zenodo separately.
PAPER = Path(
    os.environ.get(
        "EIGSEP_PAPER_NOTEBOOKS",
        "/home/christian/Documents/research/papers/eigsep_instrument/notebooks",
    )
)
FG_NPZ = PAPER / "foreground_svd.npz"
BEAM_CMP_NPZ = PAPER / "beam_comparison.npz"

# signal_loss.ipynb's substitution values, handed to beam_comparison.ipynb.
# It lives in output/ rather than the paper repo because it is a hand-off
# between notebooks, not an artifact the paper archives.
SIGNAL_LOSS_VALS = HERE / "output" / "signal_loss_vals.npz"
SHIFT_NPZ = PAPER / "horizon_shift.npz"
SIGNAL_LOSS_NPZ = PAPER / "signal_loss.npz"

# Simulation output (gitignored; see README.md for the regeneration commands).
SIMS_NPZ = HERE / "output" / "position_sims.npz"
# One nominal-horizon sidereal day per antenna (run_beam_sims.py). Same site,
# sky, horizon and times as SIMS_NPZ's nominal row -- only the beam differs.
BEAM_SIMS_NPZ = HERE / "output" / "beam_sims.npz"
HORIZONS_NPZ = HERE / "output" / "horizons_position.npz"

# Generated by models_21cm/generate.py from Zeus21 (Munoz 2023a,
# arXiv:2302.08506) with Pop III and Lyman-Werner feedback (Cruz+2024,
# arXiv:2407.18294). The npz carries its own regeneration recipe: read its
# `provenance`, `generator_source` and `env_lock` keys. Spec:
# docs/superpowers/specs/2026-08-19-zeus21-model-ensemble-design.md
MODELS_NPZ = ROOT / "models_21cm" / "output" / "zeus21_models.npz"

# The subspace dimension the paper text quotes millikelvin numbers at. NOT a
# filter depth anyone proposes to apply to data, and -- since signal_loss.pdf
# became a single panel -- not drawn in either figure: no marked line, no
# colour slice, no panel depth. What it does is keep the two notebooks quoting
# at the same dimension, so horizon_shift.ipynb compares the position
# systematic against the same retained-signal benchmark the prose uses.
#
# Derived as the smallest N at which the foreground residual falls below the
# median retained 21 cm signal and *stays* below for every larger N -- a
# reporting criterion, not a policy, because that residual is an in-sample
# optimum (horizon_shift.ipynb, section 6) and so not a benchmark real data
# could be held to.
#
# The 21 cm ensemble both notebooks filter is attenuated by the beam-weighted
# open-sky fraction eta = 1 - fgnd (mean 0.446 over the band), because both
# figures work in uncorrected antenna temperature and an isotropic signal
# enters that observable as eta(nu) * T21(nu). Without the attenuation this
# constant is 9; the factor is what moves it. See the notebooks' section 1.2.
#
# It does NOT coincide with the handover in horizon_shift.ipynb, where the
# term limiting the residual passes from the foregrounds to an unmodelled 1 m
# vertical error. That happens one mode earlier, at N = 9, and the two are
# separate landmarks: the handover is a foreground-vs-systematic crossing and
# this is a foreground-vs-signal one. They coincided before the ensemble was
# attenuated, and the prose that leaned on the coincidence has been rewritten.
# Both notebooks re-derive this value and assert it.
N_ANCHOR = 10

# Foreground modes on the residual panels' x-axis, in both figures.
N_SHOW = 18

# The beam-comparison figure runs further: the Vivaldi's foreground residual
# does not clear the retained signal until N ~ 18, so an axis that stopped at
# N_SHOW would cut off the very crossing the figure exists to show.
N_SHOW_BEAM = 25

# Antennas in beam_comparison.pdf, left to right. Order is the argument:
# chromaticity-free reference, the EIGSEP antenna, the feed the first
# suspension flew.
BEAM_ORDER = ("isotropic", "bowtie", "vivaldi")
BEAM_LABELS = {
    "isotropic": "Isotropic beam",
    "bowtie": "EIGSEP bowtie",
    "vivaldi": "Vivaldi feed",
}

# Models surviving selection.reionized_across_band out of the 4096 generated.
# Asserted in both notebooks so the two figures cannot cut different ensembles.
N_MODELS = 1769
