name: eigsim tests

on:
  push:
    branches: [main]
    paths:
      - "eigsim/**"
  pull_request:
    branches: [main]
    paths:
      - "eigsim/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv sync --dev
      - run: uv run pytest eigsim/tests -v
